"""Initial private photo library

Revision ID: 97e1eb47e302
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "97e1eb47e302"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_albums")),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("attempted", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index("attempts_address", ["address", "attempted"], unique=False)

    op.create_table(
        "photos",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("mime", sa.String(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.String(), nullable=False),
        sa.Column("uploaded_at", sa.String(), nullable=False),
        sa.Column("favorite", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photos")),
        sa.UniqueConstraint("sha256", name=op.f("uq_photos_sha256")),
    )
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_index(
            "photos_timeline",
            ["deleted_at", sa.literal_column("taken_at DESC"), sa.literal_column("id DESC")],
            unique=False,
        )

    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf", sa.String(), nullable=False),
        sa.Column("expires", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_sessions")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_users_single_owner")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "album_photos",
        sa.Column("album_id", sa.String(length=32), nullable=False),
        sa.Column("photo_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
            name=op.f("fk_album_photos_album_id_albums"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photos.id"],
            name=op.f("fk_album_photos_photo_id_photos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("album_id", "photo_id", name=op.f("pk_album_photos")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("album_photos")
    op.drop_table("users")
    op.drop_table("sessions")
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_index("photos_timeline")

    op.drop_table("photos")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index("attempts_address")

    op.drop_table("login_attempts")
    op.drop_table("albums")
    # ### end Alembic commands ###
